name: Update Signal

on:
  schedule:
    - cron: "30 23 * * *"   # codziennie 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python script.py

      - name: Commit updated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "update signal" || echo "no changes"
          git push
